SELECT * FROM sysdiagrams;

SELECT
  *
FROM
  INFORMATION_SCHEMA.TABLES;
GO


SELECT
  *
FROM
  Elanchezhiyan.INFORMATION_SCHEMA.TABLES;
GO

SELECT * FROM ELANCHEZHIYAN.INFORMATION_SCHEMA.TABLES;


CREATE TABLE EMPLOYEES
(
EMPLOYEE_ID INT PRIMARY KEY NOT NULL,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50),
HIRE_DATE DATE NOT NULL,
DEPARTMENT VARCHAR(50),
SALARY INT NOT NULL,
MOBILE_NUMBER INT NOT NULL,
EMAIL VARCHAR(50) 
);


SELECT * FROM EMPLOYEES;


