CREATE TABLE DEPARTMENTS
(
EMPLOYEE_ID INT  NOT NULL,
WORK_LOCATION VARCHAR(50),
PERMANENT_LOCATION VARCHAR(50) primary key,
WORKS_FOR VARCHAR(50),
SKILLS VARCHAR(50)
);

drop table department;

select * from DEPARTMENTS;
